#!/usr/bin/env bash

set -euo pipefail

# Dir of this scrip
export BASE_DIR="$(dirname "$(readlink -f "$0")")"

# source functions
source $BASE_DIR/ngk-functions

hostname=${HOSTNAME:-$(hostname)}

print_columns "" "${CA}$(figlet $hostname)${CN}\n"
