#!/usr/bin/env bash

set -euo pipefail

# Dir of this scrip
export BASE_DIR="$(dirname "$(readlink -f "$0")")"

# source functions
source $BASE_DIR/ngk-functions

user=${USER:-$(id -un)}
hostname=${HOSTNAME:-$(hostname)}

print_columns "Logged as" "$user@$hostname"
