#!/usr/bin/env bash

set -euo pipefail

# Dir of this scrip
export BASE_DIR="$(dirname "$(readlink -f "$0")")"

# source functions
source $BASE_DIR/ngk-functions

uptime=$(uptime -p | cut -d ' ' -f 2-)

print_columns "Uptime" "$uptime"
