#!/usr/bin/env bash

set -euo pipefail

# Dir of this scrip
export BASE_DIR="$(dirname "$(readlink -f "$0")")"

# source functions
source $BASE_DIR/ngk-functions

loads="$(cat /proc/loadavg | cut -d ' ' -f '1,2,3')"
nproc=$(nproc)
warning_threshold=$(bc -l <<< "$nproc * 0.9")
error_threshold=$(bc -l <<< "$nproc * 1.5")

text=""
for load in $loads; do
    text+="$(print_color $load $load $warning_threshold $error_threshold), "
done

print_columns "Load average" "${text::-2}"
