#!/usr/bin/env bash

set -euo pipefail

# if command exist then execute
if type "fortune" > /dev/null 2>&1 ; then

    # Dir of this scrip
    export BASE_DIR="$(dirname "$(readlink -f "$0")")"
    
    # source functions
    source $BASE_DIR/ngk-functions

    quote="$(fortune -s | fold -sw $WIDTH)"
    
    print_columns "Quote" "$quote"

fi
